# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: test
instance_flavor: uom.mse.2c9g

# Volume
volumes:
  - vol_name: demo-vol-1-1
    vol_size: 60
  - vol_name: demo-vol-1-2
    vol_size: 10
  - vol_name: demo-vol-2-1
    vol_size: 60
  - vol_name: demo-vol-2-2
    vol_size: 10
  - vol_name: demo-vol-3-1
    vol_size: 60
  - vol_name: demo-vol-3-2
    vol_size: 10
  - vol_name: demo-vol-4-1
    vol_size: 60
  - vol_name: demo-vol-4-2
    vol_size: 10

# Security group
security_groups:
  - name: public-rule
    description: "Security group for server administration and remote access (e.g. access via SSH or HTTP for Frontend)"
  - name: couchdb-rules
    description: "Security group for communication between CouchDB nodes in cluster"


security_groups_rules:
  - name: public-rule
    description: "security group for instance1 server"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: public-rule
    description: "security group for instance2 server"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: public-rule
    description: "security group for instance3 server"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: public-rule
    description: "security group for instance4 server"
    protocol: tcp
    port_range_min: 8000
    port_range_max: 8000
    remote_ip_prefix: 0.0.0.0/0

security_group_rules_db: 
  - name: couchdb-rules
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_group: couchdb-rules
  - name: couchdb-rules
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_group: couchdb-rules 
  - name: couchdb-rules
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_group: couchdb-rules


# Instance
instances:
  - name: instance1
    #security_groups: instance1-security-group
    volumes: ['demo-vol-1-1', 'demo-vol-1-2']
  - name: instance2
    #security_groups: instance2-security-group
    volumes: ['demo-vol-2-1', 'demo-vol-2-2']
  - name: instance3
    #security_groups: instance3-security-group
    volumes: ['demo-vol-3-1', 'demo-vol-3-2']
  - name: instance4
    #security_groups: instance4-security-group
    volumes: ['demo-vol-4-1', 'demo-vol-4-2']
