# deploy harvester
#
#


# run to retrieve tweets post in melbourne
- hosts: Masternode
  vars_files:
    - host_vars/environment_variables.yaml
  gather_facts: true
  roles:
    - role: twitter-crawler-mel

# run to retrieve tweets post in sydeny
- hosts: instance2
  vars_files:
    - host_vars/environment_variables.yaml
  gather_facts: true

  roles:
    - role: twitter-crawler-syd

# run to retrieve tweets post in adelaide, brisbane, darwin
- hosts: instance3
  vars_files:
    - host_vars/environment_variables.yaml
  gather_facts: true
  roles:
    - role: twitter-crawler-three

# #run to retrieve tweets post in victoria
# - hosts: instance3
#   vars_files:
#     - host_vars/environment_variables.yaml
#   gather_facts: true

#   roles:
#     - role: twitter-harvester-api


# #run to retrieve stream data for heatmap   
# - hosts: instance2
#   vars_files:
#     - host_vars/environment_variables.yaml
#   gather_facts: true

#   roles:
#     - role: twitter-harvester-api-streamer